// <auto-generated />
namespace Errogazione_Corsi_entityFrameworks_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class QuintaProva : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuintaProva));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091513210_QuintaProva"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
